# ortelius monolith
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    privileged: true
    user: root
    ports:
      - "8080:8081"
      - "50000:50000"
    networks:
      - app-network
    depends_on:
      - ortelius

  ortelius:
    container_name: ortelius
    image: quay.io/ortelius/ortelius
    privileged: true
    user: root
    platform: linux/arm64
    ports:
      - "8080:8082"
    environment:
      - DB_PASS=postgres
      - DB_USER=postgres
    volumes:
      - /tmp/postgres:/pgdata
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
